language: php

php:
  - 5.4
  - 5.5

env:
  - DB=mysql
  - DB=pgsql

before_script:
  - . tools/build/app/cakephp/travis/pre.sh

script:
  - . tools/build/app/cakephp/travis/main.sh

after_script:
  - . tools/build/app/cakephp/travis/post.sh

notifications:
  email:
    recipients:
      - netcommons3@googlegroups.com
    on_success: never  # default: change
    on_failure: always # default: always
